language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - composer require --no-interaction satooshi/php-coveralls:dev-master
  - vendor/bin/coveralls --verbose
